includes:
  - https://github.ibm.com/cloud-docs/apps
  - https://github.ibm.com/cloud-docs/activity-tracker-cli-plugin
  - https://github.ibm.com/cloud-docs/analytics-engine-cli-plugin
  - https://github.ibm.com/cloud-docs/app-configuration-cli-plugin
  - https://github.ibm.com/cloud-docs/cis-cli-plugin
  - https://github.ibm.com/cloud-docs/databases-cli-plugin
  - https://github.ibm.com/cloud-docs/cloud-functions-cli-plugin
  - https://github.ibm.com/cloud-docs/Cloudant-cli-plugin
  - https://github.ibm.com/cloud-docs/codeengine
  - https://github.ibm.com/cloud-docs/code-risk-analyzer-cli-plugin
  - https://github.ibm.com/cloud-docs/container-registry-cli-plugin
  - https://github.ibm.com/cloud-docs/devops-insights-cli-plugin
  - https://github.ibm.com/cloud-docs/dl-cli-plugin
  - https://github.ibm.com/cloud-docs/dns-svcs-cli-plugin
  - https://github.ibm.com/cloud-docs/event-notifications-cli-plugin
  - https://github.ibm.com/cloud-docs/EventStreams
  - https://github.ibm.com/cloud-docs/hs-crypto-cli-plugin
  - https://github.ibm.com/cloud-docs/hpvs-cli-plugin
  - https://github.ibm.com/cloud-docs/dbaas-cli-plugin
  - https://github.ibm.com/cloud-docs/key-protect-cli-plugin
  - https://github.ibm.com/cloud-docs/containers
  - https://github.ibm.com/cloud-docs/log-analysis-cli-plugin
  - https://github.ibm.com/cloud-docs/monitor-cli-plugin
  - https://github.ibm.com/cloud-docs/cloud-object-storage-cli-plugin
  - https://github.ibm.com/cloud-docs/openpages-cli-plugin
  - https://github.ibm.com/cloud-docs/power-iaas-cli-plugin
  - https://github.ibm.com/cloud-docs/privileged-access-gateway
  - https://github.ibm.com/cloud-docs/quantum-computing-cli-plugin
  - https://github.ibm.com/cloud-docs/secrets-manager
  - https://github.ibm.com/cloud-docs/secrets-manager-cli-plugin
  - https://github.ibm.com/cloud-docs/satellite
  - https://github.ibm.com/cloud-docs/schematics-cli-plugin
  - https://github.ibm.com/cloud-docs/tg-cli-plugin
  - https://github.ibm.com/cloud-docs/vpc-infrastructure-cli-plugin
  - https://github.ibm.com/cloud-docs/watson-query-cli-plugin
